[env]
RUST_BACKTRACE = "1"

[tasks.style]
description = "Style check on code"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.analyze]
description = "Run analysis on code"
command = "cargo"
args = ["clippy", "--all-targets"]

[tasks.check]
description = "Fast compiles"
command = "cargo"
args = ["check", "--all-targets"]

[tasks.build]
description = "Builds native release binary"
command = "cargo"
args = ["build", "--release", "--locked"]

[tasks.release]
description = "Runs release steps"
dependencies = ["style", "analyze", "check", "build"]

[tasks.build-wasm]
description = "Builds WASM binary"
install_crate = "wasm-bindgen-cli"
command = "wasm-pack"
args = ["build"]

[tasks.serve]
description = "Uses NPM to serve WASM in reload mode"
script = '''
cd www
npm run start
'''
