name: Build and upload binaries to release

on:
  create

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: wasm-game-of-life
            asset_name: wasm-game-of-life-linux-amd64
          - os: macos-latest
            artifact_name: wasm-game-of-life
            asset_name: wasm-game-of-life-macos-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Add cargo-make
        uses: davidB/rust-cargo-make@v1
      - name: Build native project
        run: cargo make build 
      - name: Build wasm
        run: cargo make build-wasm
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.event.client_payload.new_version }}
